<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Currency::upsert([
            ['currency_code' => 'AED', 'iso_code' => 2],
            ['currency_code' => 'ALL', 'iso_code' => 2],
            ['currency_code' => 'AMD', 'iso_code' => 2],
            ['currency_code' => 'ANG', 'iso_code' => 2],
            ['currency_code' => 'AOA', 'iso_code' => 2],
            ['currency_code' => 'ARS', 'iso_code' => 2],
            ['currency_code' => 'AUD', 'iso_code' => 2],
            ['currency_code' => 'AWG', 'iso_code' => 2],
            ['currency_code' => 'AZN', 'iso_code' => 2],
            ['currency_code' => 'BAM', 'iso_code' => 2],
            ['currency_code' => 'BBD', 'iso_code' => 2],
            ['currency_code' => 'BDT', 'iso_code' => 2],
            ['currency_code' => 'BGN', 'iso_code' => 2],
            ['currency_code' => 'BHD', 'iso_code' => 3],
            ['currency_code' => 'BMD', 'iso_code' => 2],
            ['currency_code' => 'BND', 'iso_code' => 2],
            ['currency_code' => 'BOB', 'iso_code' => 2],
            ['currency_code' => 'BRL', 'iso_code' => 2],
            ['currency_code' => 'BSD', 'iso_code' => 2],
            ['currency_code' => 'BWP', 'iso_code' => 2],
            ['currency_code' => 'BYN', 'iso_code' => 2],
            ['currency_code' => 'BZD', 'iso_code' => 2],
            ['currency_code' => 'CAD', 'iso_code' => 2],
            ['currency_code' => 'CHF', 'iso_code' => 2],
            ['currency_code' => 'CLP', 'iso_code' => 2],
            ['currency_code' => 'CNY', 'iso_code' => 2],
            ['currency_code' => 'COP', 'iso_code' => 2],
            ['currency_code' => 'CRC', 'iso_code' => 2],
            ['currency_code' => 'CUP', 'iso_code' => 2],
            ['currency_code' => 'CVE', 'iso_code' => 0],
            ['currency_code' => 'CZK', 'iso_code' => 2],
            ['currency_code' => 'DJF', 'iso_code' => 0],
            ['currency_code' => 'DKK', 'iso_code' => 2],
            ['currency_code' => 'DOP', 'iso_code' => 2],
            ['currency_code' => 'DZD', 'iso_code' => 2],
            ['currency_code' => 'EGP', 'iso_code' => 2],
            ['currency_code' => 'ETB', 'iso_code' => 2],
            ['currency_code' => 'EUR', 'iso_code' => 2],
            ['currency_code' => 'FJD', 'iso_code' => 2],
            ['currency_code' => 'FKP', 'iso_code' => 2],
            ['currency_code' => 'GBP', 'iso_code' => 2],
            ['currency_code' => 'GEL', 'iso_code' => 2],
            ['currency_code' => 'GHS', 'iso_code' => 2],
            ['currency_code' => 'GIP', 'iso_code' => 2],
            ['currency_code' => 'GMD', 'iso_code' => 2],
            ['currency_code' => 'GNF', 'iso_code' => 0],
            ['currency_code' => 'GTQ', 'iso_code' => 2],
            ['currency_code' => 'GYD', 'iso_code' => 2],
            ['currency_code' => 'HKD', 'iso_code' => 2],
            ['currency_code' => 'HNL', 'iso_code' => 2],
            ['currency_code' => 'HRK', 'iso_code' => 2],
            ['currency_code' => 'HTG', 'iso_code' => 2],
            ['currency_code' => 'HUF', 'iso_code' => 2],
            ['currency_code' => 'IDR', 'iso_code' => 0],
            ['currency_code' => 'ILS', 'iso_code' => 2],
            ['currency_code' => 'INR', 'iso_code' => 2],
            ['currency_code' => 'IQD', 'iso_code' => 3],
            ['currency_code' => 'ISK', 'iso_code' => 0],
            ['currency_code' => 'JMD', 'iso_code' => 2],
            ['currency_code' => 'JOD', 'iso_code' => 3],
            ['currency_code' => 'JPY', 'iso_code' => 0],
            ['currency_code' => 'KES', 'iso_code' => 2],
            ['currency_code' => 'KGS', 'iso_code' => 2],
            ['currency_code' => 'KHR', 'iso_code' => 2],
            ['currency_code' => 'KMF', 'iso_code' => 0],
            ['currency_code' => 'KRW', 'iso_code' => 0],
            ['currency_code' => 'KWD', 'iso_code' => 3],
            ['currency_code' => 'KYD', 'iso_code' => 2],
            ['currency_code' => 'KZT', 'iso_code' => 2],
            ['currency_code' => 'LAK', 'iso_code' => 2],
            ['currency_code' => 'LBP', 'iso_code' => 2],
            ['currency_code' => 'LKR', 'iso_code' => 2],
            ['currency_code' => 'LYD', 'iso_code' => 3],
            ['currency_code' => 'MAD', 'iso_code' => 2],
            ['currency_code' => 'MDL', 'iso_code' => 2],
            ['currency_code' => 'MKD', 'iso_code' => 2],
            ['currency_code' => 'MMK', 'iso_code' => 2],
            ['currency_code' => 'MNT', 'iso_code' => 2],
            ['currency_code' => 'MOP', 'iso_code' => 2],
            ['currency_code' => 'MRU', 'iso_code' => 2],
            ['currency_code' => 'MUR', 'iso_code' => 2],
            ['currency_code' => 'MVR', 'iso_code' => 2],
            ['currency_code' => 'MWK', 'iso_code' => 2],
            ['currency_code' => 'MXN', 'iso_code' => 2],
            ['currency_code' => 'MYR', 'iso_code' => 2],
            ['currency_code' => 'MZN', 'iso_code' => 2],
            ['currency_code' => 'NAD', 'iso_code' => 2],
            ['currency_code' => 'NGN', 'iso_code' => 2],
            ['currency_code' => 'NIO', 'iso_code' => 2],
            ['currency_code' => 'NOK', 'iso_code' => 2],
            ['currency_code' => 'NPR', 'iso_code' => 2],
            ['currency_code' => 'NZD', 'iso_code' => 2],
            ['currency_code' => 'OMR', 'iso_code' => 3],
            ['currency_code' => 'PAB', 'iso_code' => 2],
            ['currency_code' => 'PEN', 'iso_code' => 2],
            ['currency_code' => 'PGK', 'iso_code' => 2],
            ['currency_code' => 'PHP', 'iso_code' => 2],
            ['currency_code' => 'PKR', 'iso_code' => 2],
            ['currency_code' => 'PLN', 'iso_code' => 2],
            ['currency_code' => 'PYG', 'iso_code' => 0],
            ['currency_code' => 'QAR', 'iso_code' => 2],
            ['currency_code' => 'RON', 'iso_code' => 2],
            ['currency_code' => 'RSD', 'iso_code' => 2],
            ['currency_code' => 'RUB', 'iso_code' => 2],
            ['currency_code' => 'RWF', 'iso_code' => 0],
            ['currency_code' => 'SAR', 'iso_code' => 2],
            ['currency_code' => 'SBD', 'iso_code' => 2],
            ['currency_code' => 'SCR', 'iso_code' => 2],
            ['currency_code' => 'SEK', 'iso_code' => 2],
            ['currency_code' => 'SGD', 'iso_code' => 2],
            ['currency_code' => 'SHP', 'iso_code' => 2],
            ['currency_code' => 'SLE', 'iso_code' => 2],
            ['currency_code' => 'SOS', 'iso_code' => 2],
            ['currency_code' => 'SRD', 'iso_code' => 2],
            ['currency_code' => 'STN', 'iso_code' => 2],
            ['currency_code' => 'SVC', 'iso_code' => 2],
            ['currency_code' => 'SZL', 'iso_code' => 2],
            ['currency_code' => 'THB', 'iso_code' => 2],
            ['currency_code' => 'TND', 'iso_code' => 3],
            ['currency_code' => 'TOP', 'iso_code' => 2],
            ['currency_code' => 'TRY', 'iso_code' => 2],
            ['currency_code' => 'TTD', 'iso_code' => 2],
            ['currency_code' => 'TWD', 'iso_code' => 2],
            ['currency_code' => 'TZS', 'iso_code' => 2],
            ['currency_code' => 'UAH', 'iso_code' => 2],
            ['currency_code' => 'UGX', 'iso_code' => 0],
            ['currency_code' => 'USD', 'iso_code' => 2],
            ['currency_code' => 'UYU', 'iso_code' => 2],
            ['currency_code' => 'UZS', 'iso_code' => 2],
            ['currency_code' => 'VEF', 'iso_code' => 2],
            ['currency_code' => 'VND', 'iso_code' => 0],
            ['currency_code' => 'VUV', 'iso_code' => 0],
            ['currency_code' => 'WST', 'iso_code' => 2],
            ['currency_code' => 'XAF', 'iso_code' => 0],
            ['currency_code' => 'XCD', 'iso_code' => 2],
            ['currency_code' => 'XOF', 'iso_code' => 0],
            ['currency_code' => 'XPF', 'iso_code' => 0],
            ['currency_code' => 'YER', 'iso_code' => 2],
            ['currency_code' => 'ZAR', 'iso_code' => 2],
            ['currency_code' => 'ZMW', 'iso_code' => 2]
        ],['currency_code', 'iso_code']);
    }
}
